title: "Lého Dehove, Bio-Mechatronics & Robotics"
description: "R&D Engineering Student specialized in Bio-Mechatronics, Control Systems, Kinematics and Embedded Robotics."
url: "https://dehoveleho.github.io"
markdown: kramdown
plugins: []